[target.x86_64-unknown-linux-musl]
pre-build = [
    "apt-get update && apt-get install -y perl make cmake"
]

[target.aarch64-unknown-linux-musl]
pre-build = [
    "apt-get update && apt-get install -y perl make cmake"
]