[target.x86_64-unknown-linux-musl]
pre-build = [
    "apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y perl make cmake gcc"
]

[target.x86_64-unknown-linux-musl.env]
volumes = []
OPENSSL_STATIC = "1"
OPENSSL_VENDORED = "1"

[target.aarch64-unknown-linux-musl]
pre-build = [
    "apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y perl make cmake gcc-aarch64-linux-gnu"
]

[target.aarch64-unknown-linux-musl.env]
volumes = []
OPENSSL_STATIC = "1"
OPENSSL_VENDORED = "1"

[build.env]
passthrough = [
    "OPENSSL_STATIC",
    "OPENSSL_VENDORED",
]