[target.x86_64-unknown-linux-musl]
pre-build = [
    "apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y perl make cmake"
]

[target.aarch64-unknown-linux-musl]
pre-build = [
    "apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y perl make cmake"
]

[build.env]
passthrough = [
    "OPENSSL_STATIC",
    "OPENSSL_VENDORED", 
    "OPENSSL_NO_PKG_CONFIG",
]