[target.x86_64-unknown-linux-musl]
pre-build = [
    "apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y perl make cmake gcc musl-tools"
]

[target.aarch64-unknown-linux-musl]
pre-build = [
    "apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y perl make cmake gcc-aarch64-linux-gnu musl-tools"
]