version: "3.8"

services:
  stakgraph:
    image: standalone:latest
    # image: ghcr.io/stakwork/stakgraph-standalone:latest
    container_name: stakgraph
    ports:
      - 7799:7799
    environment:
      - PORT=7799
      - RUST_LOG=debug
      - RUST_BACKTRACE=1
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=testtest

  neo4j:
    image: sphinxlightning/sphinx-neo4j:latest
    container_name: neo4j
    volumes:
      - ./.neo4j/data:/data:rw
      - ./.neo4j/logs:/logs:rw
      - ./.neo4j/plugins:/plugins:rw
      - ./.neo4j/tmp/import:/import
      - ./conf:/conf/
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/testtest
    command: >
      /bin/bash -c "
      cp -R /var/lib/neo4j/plugins/* /plugins &&
      /startup/docker-entrypoint.sh neo4j
      "
    healthcheck:
      test:
        [
          "CMD",
          "/var/lib/neo4j/bin/cypher-shell",
          "-u",
          "neo4j",
          "-p",
          "testtest",
          "MATCH (n) RETURN n LIMIT 1",
        ]
      interval: 10s
      timeout: 10s
      retries: 20
