name: Build CLI

on:
  push:
    tags:
      - "v*"

jobs:
  build-cli:
    runs-on: ${{ matrix.build-on }}
    strategy:
      matrix:
        include:
          # Linux
          - target: x86_64-unknown-linux-gnu
            archive: tar.gz
            build-on: ubuntu-latest
            use-cross: false
          - target: aarch64-unknown-linux-gnu
            archive: tar.gz
            build-on: ubuntu-latest
            use-cross: true
          # macOS - separate runners for each arch
          - target: x86_64-apple-darwin
            archive: tar.gz
            build-on: macos-13 # ← Intel runner
            use-cross: false
          - target: aarch64-apple-darwin
            archive: tar.gz
            build-on: macos-latest # ← Apple Silicon runner
            use-cross: false
          # Windows
          - target: x86_64-pc-windows-gnu
            archive: zip
            build-on: ubuntu-latest
            use-cross: true

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - name: Install system dependencies (Linux native)
        if: matrix.target == 'x86_64-unknown-linux-gnu'
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libssl-dev

      - name: Install system dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install openssl@3

      - name: Install cross
        if: matrix.use-cross
        run: cargo install cross --git https://github.com/cross-rs/cross

      - name: Add target
        run: rustup target add ${{ matrix.target }}

      - name: Build (native)
        if: ${{ !matrix.use-cross }}
        run: cargo build --release --target ${{ matrix.target }} --bin stakgraph

      - name: Build with cross
        if: matrix.use-cross
        env:
          CROSS_NO_WARNINGS: 0
        run: cross build --release --target ${{ matrix.target }} --bin stakgraph

      - name: Package (Unix)
        if: matrix.archive == 'tar.gz'
        run: |
          cd target/${{ matrix.target }}/release
          tar czf stakgraph-${{ matrix.target }}.tar.gz stakgraph

      - name: Package (Windows)
        if: matrix.archive == 'zip'
        run: |
          cd target/${{ matrix.target }}/release
          zip stakgraph-${{ matrix.target }}.zip stakgraph.exe

      - uses: actions/upload-artifact@v4
        with:
          name: stakgraph-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/stakgraph-${{ matrix.target }}.${{ matrix.archive }}

  release:
    needs: build-cli
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4

      - uses: softprops/action-gh-release@v1
        with:
          files: stakgraph-*/stakgraph-*.*
