name: Stakgraph Standalone Test
on:
  pull_request:
    branches:
      - main

jobs:
  run-standalone-test:
    runs-on: ubuntu-latest
    name: Run standalone tests
    steps:
      - name: Enable docker.host.internal for Ubuntu
        run: |
          pwd && sudo bash -c 'echo "172.17.0.1 host.docker.internal" >> /etc/hosts'

      - name: Checkout from Github
        uses: actions/checkout@v4

      - name: Setup Rust cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-v2-${{ hashFiles('**/Cargo.lock') }}

      - name: Give Permission
        working-directory: ./mcp
        run: |
          mkdir -p ./.neo4j/plugins
          sudo chown -R 1000:1000 ./.neo4j/plugins
          sudo chmod -R 777 ./.neo4j/plugins  
          sudo chmod -R 777 ./conf

      - name: Run Neo4j
        working-directory: ./mcp
        run: docker compose -f neo4j.yaml up -d

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.1"

      - name: Verify Go Installation
        run: go version

      - name: Install gopls
        run: go install golang.org/x/tools/gopls@latest

      - name: Verify gopls Installation
        run: |
          echo "$HOME/go/bin" >> $GITHUB_PATH
          gopls version

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Verify Node.js Installation
        run: node -v

      - name: Install TypeScript and TypeScript LSP
        run: |
          npm install -g typescript typescript-language-server
          echo "$HOME/.npm-global/bin" >> $GITHUB_PATH

      - name: Verify TypeScript Installation
        run: |
          tsc --version
          typescript-language-server --version

      - name: Wait for Neo4j to be Ready
        run: |
          echo "Waiting for Neo4j to be healthy..."
          timeout 300s sh -c '
          until docker inspect --format "{{json .State.Health.Status }}" neo4j.sphinx | grep -q "healthy"; do
            echo "Neo4j is not ready yet..."
            sleep 10
          done'
          echo "Neo4j is healthy!"

      - name: Run Rust Tests behind Neo4j
        run: |
          export USE_LSP=false
          cargo test --features neo4j -- --test-threads=1

      - name: Run Graph Update Tests
        run: |
          export TEST_REF_ID="test_ref_id"
          export LSP_SKIP_POST_CLONE=1
          export USE_LSP=false
          cargo test --features neo4j test_graph_update --verbose

      - name: Run Graph Consistency Test
        run: |
          export LSP_SKIP_POST_CLONE=1
          export USE_LSP=false
          cargo test --features neo4j test_graph_consistency --verbose

      - name: Cleanup
        if: always()
        run: |
          if [ -f standalone.pid ]; then
            kill $(cat standalone.pid) || true
          fi
          docker compose -f ./mcp/neo4j.yaml down
